# Generated by Django 4.2.9 on 2024-02-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetNestApp', '0003_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Wallet_Address',
            field=models.CharField(default='0x0000000000000000000000000000000000', max_length=50),
        ),
    ]
