# Generated by Django 4.2.9 on 2024-02-15 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("BetNestApp", "0004_alter_userprofile_wallet_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bet",
            fields=[
                ("Staker_name", models.CharField(default="Anonymous", max_length=50)),
                (
                    "Staker_KEY",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.BigIntegerField(default=0)),
                ("odds", models.CharField(default=0, max_length=50)),
            ],
        ),
    ]
