# Generated by Django 4.2.9 on 2024-02-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BetNestApp", "0005_bet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="Staker_name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="BetNestApp.userprofile"
            ),
        ),
    ]
