# Generated by Django 4.2.9 on 2024-02-15 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BetNestApp", "0006_alter_bet_staker_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="Is_Winner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bet",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 15, 19, 28, 17, 47530)
            ),
        ),
        migrations.AddField(
            model_name="bet",
            name="game_category",
            field=models.CharField(default="none", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="balance",
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField(default=0)),
                ("odds", models.CharField(default=0, max_length=50)),
                (
                    "Payment_Date",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 2, 15, 19, 28, 17, 48530)
                    ),
                ),
                (
                    "Beneficiary_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BetNestApp.userprofile",
                    ),
                ),
            ],
        ),
    ]
