# Generated by Django 4.2.9 on 2024-02-15 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BetNestApp", "0007_bet_is_winner_bet_date_bet_game_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 15, 19, 28, 45, 223783)
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="Payment_Date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 15, 19, 28, 45, 223783)
            ),
        ),
    ]
