# Generated by Django 4.2.9 on 2024-02-15 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BetNestApp", "0008_alter_bet_date_alter_payment_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 15, 21, 20, 43, 867740)
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="Payment_Date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 15, 21, 20, 43, 867740)
            ),
        ),
    ]
