# Generated by Django 4.2.9 on 2024-02-15 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BetNestApp", "0009_alter_bet_date_alter_payment_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="Staker_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="BetNestApp.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 15, 21, 25, 4, 681576)
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="Beneficiary_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="BetNestApp.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="Payment_Date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 15, 21, 25, 4, 681576)
            ),
        ),
    ]
