# Generated by Django 4.2.9 on 2024-02-15 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BetNestApp", "0010_alter_bet_staker_name_alter_bet_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_address",
                    models.CharField(default="anonymous@gmail.com", max_length=50),
                ),
                ("message", models.TextField()),
                (
                    "Complaint_Date",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 2, 15, 21, 50, 9, 149247)
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bet",
            name="game_title",
            field=models.CharField(default="Lakers VS Bucks", max_length=250),
        ),
        migrations.AlterField(
            model_name="bet",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 15, 21, 50, 9, 148246)
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="Payment_Date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 15, 21, 50, 9, 149247)
            ),
        ),
    ]
